// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtOCe6KO3_-wFBwBCKrX6bEbhugM8jHUw',
    appId: '1:938145302049:web:9cc5690351a57144d14560',
    messagingSenderId: '938145302049',
    projectId: 'cook-book-af0b4',
    authDomain: 'cook-book-af0b4.firebaseapp.com',
    storageBucket: 'cook-book-af0b4.firebasestorage.app',
    measurementId: 'G-YEDHXZY623',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU0UQQOtV82hJe-3_DYXsX_qHu8amvaiI',
    appId: '1:938145302049:android:58ebc76d04893c38d14560',
    messagingSenderId: '938145302049',
    projectId: 'cook-book-af0b4',
    storageBucket: 'cook-book-af0b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-8b9XMVnINN5sfQptyNNd0rbQlmULmn8',
    appId: '1:938145302049:ios:9f14f04f791e21d4d14560',
    messagingSenderId: '938145302049',
    projectId: 'cook-book-af0b4',
    storageBucket: 'cook-book-af0b4.firebasestorage.app',
    iosBundleId: 'com.example.recipeBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-8b9XMVnINN5sfQptyNNd0rbQlmULmn8',
    appId: '1:938145302049:ios:9f14f04f791e21d4d14560',
    messagingSenderId: '938145302049',
    projectId: 'cook-book-af0b4',
    storageBucket: 'cook-book-af0b4.firebasestorage.app',
    iosBundleId: 'com.example.recipeBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtOCe6KO3_-wFBwBCKrX6bEbhugM8jHUw',
    appId: '1:938145302049:web:2ca2d8fdeccc95a0d14560',
    messagingSenderId: '938145302049',
    projectId: 'cook-book-af0b4',
    authDomain: 'cook-book-af0b4.firebaseapp.com',
    storageBucket: 'cook-book-af0b4.firebasestorage.app',
    measurementId: 'G-WF35CG6EGW',
  );
}
